apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qwt92ycs0-python 
  janus-idp.io/tekton: qwt92ycs0-python
  backstage.io/kubernetes-id: qwt92ycs0-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qwt92ycs0-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  